### ISSUE TITLE
Feature Request: Allow many styles

### ISSUE THREAD

**Issue by muescha** [retextjs/retext-syntax-mentions#7]
### Subject of the feature

we can also allow `style: ['github', 'twitter', customRegEx]`

https://github.com/retextjs/retext-syntax-mentions/issues/6#issuecomment-618278732

### Problem

if you have GitHub and Twitter mentions in the docs then it would be nice to have both to check

### Expected behavior

use many styles from the settings

### Alternatives

```javascript
        .use(require("retext-syntax-mentions"), { style: 'github'})
        .use(require("retext-syntax-mentions"), { style: 'twitter'})
```

~call the `retext-syntax-mentions` 2x times with different options~ 

EDIT: this is not possible, the last option wins in this case and only the test for `twitter` is run :(

**Comment by wooorm** [comment]
- Using the same plugin multiple times, uses it once, but merges the options. See for example https://github.com/unifiedjs/unified/issues/79.
- If you have different types of mentions, then, well, it’s the same as a relaxed regex, no? E.g., you can pass `/^@\w{1,40}$/i` and it’ll support most kinds of mentions?

**Comment by muescha** [comment]
no it not used the sames, because there are some `@component/something-different` in the code and then they are errors :(

for example also in mdx files with an import this also get ignored :/

```mdx
import VisuallyHidden from "@components/visually-hidden"
```

**Comment by wooorm** [comment]
Well, `@component/something-different` is a valid GitHub mention: it mentions the `something-different` team in the `component` organization, so if that behavior is not what you want, then I’d suggest using `twitter` or a custom regex.

If you want to check MDX files: those are fundamentally different than Markdown, and becoming more so in MDX@2. You may want use `remark-mdx` to support the MDX-only/non-Markdown syntax as *syntax*. But you may need to use separate processors: one for regular Markdown, that doesn‘t support imports, and one for MDX!

**Comment by muescha** [comment]
it is used here: https://github.com/gatsbyjs/gatsby/pull/24372 but the docs are mixed normal markdown and some mdx (but same ending)

**Comment by wooorm** [comment]
For the original question: I view “Many styles” as technically a new style, and that can be done with a regex. I believe I can close this?

---

For your other question:

> The docs are mixed normal markdown and some mdx (but same ending)

When you say “same ending”, I understand that as the same extension (`.md`), correct? If that is the case, I would strongly suggest using `.mdx` as an extension (see https://github.com/jshttp/mime-db/pull/160). That may be a big task for Gatsby, so you may want to talk to other Gatsby folks about that. But by using the same extension for different content types, tools can’t understand that the content is different (and it fundamentally is, especially with the upcoming MDX@2).

**Comment by muescha** [comment]
yes - for markdown files and mdx files are used the same file extension `.md`

is it possible to process all files with `remark-mdx` with no problems?

**Comment by wooorm** [comment]
> is it possible to process all files with remark-mdx with no problems?

It is somewhat possible currently, in a couple of weeks with MDX@2 it definitely isn’t. See my earlier reply:

> But by using the same extension for different content types, tools can’t understand that the content is different (and it fundamentally is, especially with the upcoming MDX@2).

**Comment by wooorm** [comment]
Alright, I’ll close this as different styles can be achieved with a custom regex. As you don‘t care for GH teams, I’d suggest:

```js
  .use(syntaxMentions, {style: /^@\w{1,40}$/})
```

**Comment by muescha** [comment]
thats not include the `-` for example: `@m-allanson`

**Comment by ChristianMurphy** [comment]
then add `-` to the custom regex :slightly_smiling_face: 
here's a resource to help with creating regexs https://regexr.com

**Comment by muescha** [comment]
thx for the link :)


```javascript
 .use(syntaxMentions, {style: /^@[\w-]{1,40}$/})
```

i was not aware that i can put `\w` inside brackets :)
