### ISSUE TITLE
Feature Request: Check for String / RegEx

### ISSUE THREAD

**Issue by muescha** [retextjs/retext-syntax-mentions#8]
### Subject of the feature

when i have a string other than `twitter` or `github` 

```javascript
.use(require("retext-syntax-mentions"), { style: 'twittter'})
```

```
TypeError: style.test is not a function
```

### Problem

the code did not check after init if it is an RegEx

### Expected behavior

Should print a error that an RegEx is required

### Alternatives

n/a

**Comment by wooorm** [comment]
Ah good catch, there indeed is no error for incorrect configuration. Interested in creating a PR?

**Comment by wooorm** [comment]
Released!
